### ISSUE TITLE
References to /etc/pacman.d/arcolinux-mirrorlist in archiso/pacman.conf

### ISSUE THREAD

**Issue by hlestrat** [arconetpro/arconet-iso#1]
Hello,

I was wondering why do you reference /etc/pacman.d/arcolinux-mirrorlist directly in the archiso/pacman.conf ? This means that the host machine has to have the arcolinux mirror list (which is not my case, since I am using a pure arch installation). I did change that by a local copy (wget https://raw.githubusercontent.com/arcolinux/arcolinux-mirrorlist/master/etc/pacman.d/arcolinux-mirrorlist) and then reference ./arcolinux.mirrorlist in pacman.conf.

https://github.com/arconetpro/arconet-iso/blob/85f3f3e0632aca7844969eb198312e37001aa8ef/archiso/pacman.conf#L76C11-
L76C45

But perhaps it was on purpose to let us find other ways ?

Anyway, great work :)

Best regards,

H

**Comment by arcolinuxz** [comment]
It is on purpose as we have more than one server - then it is best to use a file containing all servers

Arch users need to get the keys and mirrors in.

That is what the arcolinux-spices is for.

See home page https://arcolinux.info

down the bottom of the page
